# vim: ft=dosini
# pywal 生成，勿手改；源模板 ~/.config/wal/templates/colors-fcitx5.conf
[Metadata]
Name=wal
Version=1.0
Author=pywal
Description=Colors from pywal
ScaleWithDPI=True

[InputPanel]
Font=Sans 13
Spacing=6

NormalColor={foreground}
HighlightCandidateColor={foreground}
HighlightColor={foreground}
HighlightBackgroundColor=#1792D0

[InputPanel/TextMargin]
Left=14
Right=14
Top=8
Bottom=8

[InputPanel/Background]
Color=#000000

[InputPanel/Background/Margin]
Left=8
Right=8
Top=8
Bottom=8

[InputPanel/Highlight]
Color=#1792D0

[InputPanel/Highlight/Margin]
Left=14
Right=14
Top=6
Bottom=6

[Menu]
Font=Sans 10
NormalColor={foreground}
HighlightCandidateColor={foreground}
Spacing=6

[Menu/Background]
Color=#000000

[Menu/Background/Margin]
Left=2
Right=2
Top=2
Bottom=2

[Menu/ContentMargin]
Left=4
Right=4
Top=4
Bottom=4

[Menu/Highlight]
Color=#1792D0

[Menu/Highlight/Margin]
Left=10
Right=10
Top=5
Bottom=5

[Menu/Separator]
Color=#1792D0

[Menu/TextMargin]
Left=5
Right=5
Top=5
Bottom=5
